#!/bin/bash
PROG="Corn_finnKt"
if test $# -eq 1
then
	TIME=time
else
	TIME=""
fi
testcase=1

while true
do
	infile=`printf "../../data/sample/%d.in" $testcase`
	ansfile=`printf "../../data/sample/%d.ans" $testcase`
	if ! test -e "$infile"
	then
		break
	fi
	$TIME runkotlin $PROG < $infile >z
	diff $ansfile z >zz
	if test -s zz
	then echo $ansfile
		cat zz
	fi
	testcase=$((testcase+1))
done

testcase=1001

while true
do
	infile=`printf "../../data/secret/%d.in" $testcase`
	ansfile=`printf "../../data/secret/%d.ans" $testcase`
	if ! test -e "$infile"
	then
		break
	fi
	$TIME runkotlin $PROG < $infile >z
	diff $ansfile z >zz
	if test -s zz
	then echo $ansfile
		cat zz
	fi
	testcase=$((testcase+1))
done
rm -f z zz
